### ISSUE TITLE
drop_caches may never finish

### ISSUE THREAD

**Issue by onlyjob** [akiradeveloper/dm-writeboost#57]
`drop_caches` never finish if device is used by _cryptsetup_. When encrypted device is activated on top of writeboost device the following command do not exit or return error:

     dmsetup message wb_luks01 0 drop_caches

I can successfully deconstruct writeboost device with `dmsetup remove wb_luks01`.

It could be that `drop_caches` is unable to drop dirty caches at all as even when I de-activate cryptsetup device  `drop_caches` still never exit...

**Comment by akiradeveloper** [comment]
Nice test. Thanks.

I want to ask you several things please corporate.

* You can see how many dirty_caches remains by `dmsetup status`. Please tell me the result first.  
* Also, I want to know what is the `dmsetup create` command line you executed.
* What is the kernel version you are based on?
* No sign of bug by seeing dmesg?
* To isolate the problem, make sure that the problem "drop_caches never exit" never reproduce without cryptsetup (do you mean this by the last paragraph?)

My tests in [device-mapper-test-suite](https://github.com/jthornber/device-mapper-test-suite) uses drop_caches so I don't believe it is completely dumb but it might happen that the dirty cache count occasionally goes crazy (of course it's bug).

**Comment by onlyjob** [comment]
> You can see how many dirty_caches remains by dmsetup status.

Not sure which number represent `dirty_caches`:
~~~~
wb_luks01: : 0 3907029168 writeboost 429007 969010 7630 3379 3378 3378 1 3 246522 0 0 1 5 0 0 0 29220 0 0 0 7375 0 0 1641 14 allow_writeback 1 enable_writeback_modulator 1 writeback_threshold 70 nr_cur_batched_writeback 32 sync_data_interval 3600 update_sb_record_interval 0 read_cache_threshold 0
~~~~

> Also, I want to know what is the dmsetup create command line you executed.

Something like `dmsetup create wb_luks01 --table "0 $(blockdev --getsize /dev/disk/by-uuid/2e8260bc-024c-4252-a695-a73898c974c7) writeboost /dev/disk/by-uuid/2e8260bc-024c-4252-a695-a73898c974c7 /dev/disk/by-partuuid/43372b68-3407-45fa-9b2f-61afe9c26a68"`. It works very well as long as I do not attempt to `drop_caches`.

> What is the kernel version you are based on?

`3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux`

> No sign of bug by seeing dmesg?

Nothing whatsoever.

> To isolate the problem, make sure that the problem "drop_caches never exit" never reproduce without cryptsetup (do you mean this by the last paragraph?)

How? And why? I create writeboost device; activate cryptsetup device on top of it; deactivate cryptsetup device; `drop_caches` (where it fails)...

**Comment by akiradeveloper** [comment]
What version of dm-writeboost are you using? v1.0.1?

> Not sure which number represent dirty_caches:

Sorry this is really cryptic (I am making a program to prettify the result). It says only one dirty block left on the cache disk... seems to be a bug. This is what I saw in early development and not see recently.

> 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux

The kernel version is ok.

> How? And why? I create writeboost device; activate cryptsetup device on top of it; deactivate cryptsetup device; drop_caches (where it fails)...

I think you ran some synthetic benchmark test (maybe, near 1GB) between activate and deactivate. I can see that from the status line.

Theoretically, cryptsetup doesn't cause anything bad to dirty cache count but please just remove activate and deactivate pair to remove the possibility of cryptsetup doing bad things. Careful step-by-step analysis only can solve this problem (because I am not there with you). So please test the following two basic steps

Step1:
1. create writeboost device
2. drop_caches

Step2:
// reboot and reformat the cache device
1. create writeboost device
2. do the same benchmark
3. drop_caches

**Comment by onlyjob** [comment]
> What version of dm-writeboost are you using? v1.0.1?

Yes, 1.0.1.

> I think you ran some synthetic benchmark test (maybe, near 1GB) between activate and deactivate. I can see that from the status line.

Not quite, I just pasted status from live system. I can never drop caches once I've touched writeboost device. Even if I've changed absolutely nothing and just added and removed cryptsetup device.

Step1 works.

Step2 does not work, as described above (no benchmark; cryptsetup device created  and immediately removed; no other activity).

**Comment by akiradeveloper** [comment]
> Not quite, I just pasted status from live system. 

You can't reboot the system?

Did you zero out the first one sector of the cache device before Step2? I want to know in which point did you reformat the cache device because v1.0.1 should fix a critical bug in resuming a cache.

I guess what you did is

1. zero out the sector
2. dmsetup create
3. drop_caches => OK
4. dmsetup remove
5. dmsetup create => this causes resuming the previous cache state
6. cryptsetup create/remove
7. dmsetup drop_cache => Not OK

Right?

But the known issue (that's fixed in v1.0.1) should happen on a condition that read caching is enabled but it isn't in your setting. So strange.

All I can do at this stage is

- try to reproduce the problem.
- read through again the driver code to find out imbalanced pair of inc/dec dirty cache count.

**Comment by akiradeveloper** [comment]
Probably I solved this issue.

Look at this code in my device-mapper-test-suite. This `drop_cache` method clean up all the dirty caches. The comment says that the dirty caches on RAM buffer are never written back because they aren't yet flushed to the cache device. Iow, drop_caches message only writes back dirty caches on the cache device.

```ruby
  def drop_caches
    return unless is_wb?
    cleanup_forcibly

    # We need the sync daemon works while waiting for dirty
    # caches all written back. Otherwise drop_caches message
    # may never return because of dirty caches remain on RAM
    # buffer that is submitted from upper layer after
    # drop_caches started.
    @wb.message(0, "sync_interval", 1)
    @wb.message(0, "drop_caches")
  end
```

I think you have one dirty cache on the RAM buffer (it's really occasional though). So you need to set sync_interval to 1 (flush caches on RAM buffer every seconds) before send drop_caches as the code above.

If you are still holding the system in problem, type Ctrl-C to exit drop_caches message (it's interruptible) and send message `sync_interval 1` to the device and send drop_caches again.

**Comment by onlyjob** [comment]
> You can't reboot the system?

I've never said that. I can reboot my system but I'd like to be able to drop_caches before that...

I did zero out the whole caching device before creating writeboost device for the first time. Problem immediately manifested. I've never used dm-writeboost prior to version 1.0.1.

I tried setting `sync_data_interval 1` but it did not have any effect on the problem (`drop_caches` still hangs).

I'll explain again what is happening:

 1. dmsetup create
 2. drop_caches => OK
 3. cryptsetup create/remove
 4. dmsetup drop_cache => Not OK

**Comment by akiradeveloper** [comment]
I tried some work on this issue.

`drop_caches` works as I expect in the following script. Without setting `sync_data_interval 1`, the second `drop_caches` never return. I didn't use cryptsetup here but do some writes by dd command.

Please first run this script (after changing the device paths) in your system "after reboot". I ask you to test after reboot because I want to see a result that's run in a cleaner environment.

Btw, why I didn't use cryptsetup is I don't know how to use it. Please tell me the exact command lines to create/remove cryptsetup. I will try in my system.

```
modprobe dm-writeboost
B=/dev/hvg2/back18g
C=/dev/hvg1/cache2g
sz=`blockdev --getsize $B`
# A = B+C
A=/dev/mapper/wbdev

dd if=/dev/zero of=$C count=1 # will reformat the cache device
dmsetup create wbdev --table "0 $sz writeboost $B $C"
dmsetup message wbdev 0 drop_caches # always returns
dd if=/dev/zero of=$A count=1234 # do some works. left dirties on the RAM buffer
dmsetup status wbdev
dmsetup message wbdev 0 sync_data_interval 1 # without this line, the next drop_caches never return
dmsetup message wbdev 0 drop_caches
dmsetup status wbdev
dmsetup remove wbdev
```

**Comment by onlyjob** [comment]
A already tried to reboot system over the weekend when I was learning about this issue. In fact I rebooted several times and always was able to reproduce the problem.
However I may not be able to reboot my system again until next opportunity window probably around next weekend.

Using cryptsetup is easy:

    cryptsetup luksFormat {device}
    cryptsetup open --type luks {device} {name}

Where `name` is a device-mapper name of the unlocked encrypted disk.
`device` is an encrypted block device. `luksFormat` needs to be used only once. see [cryptsetup(8)](http://manpages.debian.org/cgi-bin/man.cgi?query=cryptsetup&apropos=0&sektion=0&manpath=Debian+8+jessie&format=html&locale=en) for details.

**Comment by akiradeveloper** [comment]
I modified the script and tried again. And the result was OK; It runs through the end and the status line looks benign. It doesn't reproduce in my system. why..

Please run the previous script with dd and please report the output of `cat /proc/diskstats` and `lsblk` while the `drop_caches` is stuck. Probably, some writes are still in flight.

```sh
modprobe dm-writeboost
B=/dev/hvg2/back18g
C=/dev/hvg1/cache2g
sz=`blockdev --getsize $B`
# A = B+C
A=/dev/mapper/wbdev

dd if=/dev/zero of=$C count=1 # will reformat the cache device
dmsetup create wbdev --table "0 $sz writeboost $B $C"
dmsetup message wbdev 0 drop_caches # always returns

# do some works
# 1 (simple dd)
#dd if=/dev/zero of=$A count=1234 # do some works
# 2 (cryptsetup)
cryptsetup luksFormat $A
cryptsetup open --type luks $A luksdev
cryptsetup remove luksdev

dmsetup status wbdev
dmsetup message wbdev 0 sync_data_interval 1 # without this line, the next drop_caches never return
dmsetup message wbdev 0 drop_caches
dmsetup status wbdev
dmsetup remove wbdev
```

**Comment by onlyjob** [comment]
I'll see what I can do. Besides you seems to be able to reproduce the issue already if `drop_caches` get stuck without prior `sync_data_interval 1`.
Perhaps `drop_caches` should work disregarding of `sync_data_interval` and even when some writes are still in flight. In any case it should either return failure or finish successfully. Maybe it should have been called `flush_caches` to avoid doubts.

I think short-term solution might be if you identify where it is getting stuck and escape/abort from there with error...

**Comment by akiradeveloper** [comment]
So this is the design issue.

The case is that some dirty data is still on the RAM buffer and the `drop_caches` never return until all dirty data become persistent, meaning they are hit on HDD.

> Perhaps drop_caches should work disregarding of sync_data_interval and even when some writes are still in flight. In any case it should either return failure or finish successfully. Maybe it should have been called flush_caches to avoid doubts.

I don't like the idea that `drop_caches` should flush the volatile data to the SSD because it violates single responsibility principle. So I left the message only dropping caches on the SSD.

Instead, I need you to do this way. You should suspend the device before `drop_caches`. This is natural because when you execute `drop_caches` is when you don't need to accept any IOs.

```sh
dmsetup suspend wbdev
dmsetup message wbdev 0 drop_caches
dmsetup resume wbdev
```

How this works is postsuspend hook flushes volatile data on the RAM buffer which is done by `flush_current_buffer`.

```c
/*
 * .postsuspend is called before .dtr.
 * We flush out all the transient data and make them persistent.
 */
static void writeboost_postsuspend(struct dm_target *ti)
{
	int r = 0;
	struct wb_device *wb = ti->private;
	flush_current_buffer(wb);
	maybe_IO(blkdev_issue_flush(wb->cache_dev->bdev, GFP_NOIO, NULL));
}
```

**Comment by onlyjob** [comment]
Here is relevant part of `lsblk` while `dmsetup message lizard_m04 0 drop_caches` is stuck:

~~~~
NAME           MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda              8:0    0   1.8T  0 disk  
└─lizard_m01   253:0    0   1.8T  0 dm    
sdb              8:16   0   1.8T  0 disk  
└─lizard_m04   253:5    0   1.8T  0 dm    
sdc              8:32   0   1.8T  0 disk  
└─lizard_m02   253:1    0   1.8T  0 dm    
sdd              8:48   0   1.8T  0 disk  
└─lizard_m03   253:3    0   1.8T  0 dm    
sde              8:64   0   2.7T  0 disk  
└─lizard_m05   253:7    0   2.7T  0 dm    
sdh              8:112  0  18.7G  0 disk  
├─sdh1           8:113  0   3.7G  0 part  
│ └─lizard_m01 253:0    0   1.8T  0 dm    
├─sdh2           8:114  0   3.7G  0 part  
│ └─lizard_m02 253:1    0   1.8T  0 dm    
├─sdh3           8:115  0   3.7G  0 part  
│ └─lizard_m03 253:3    0   1.8T  0 dm    
├─sdh4           8:116  0   3.7G  0 part  
│ └─lizard_m04 253:5    0   1.8T  0 dm    
└─sdh5           8:117  0   3.7G  0 part  
  └─lizard_m05 253:7    0   2.7T  0 dm    
~~~~

`cat /proc/diskstats`:

~~~~
   8       0 sda 11452 56285 541918 1216132 15483 312191 2619112 2206468 0 104856 3422568
   8      16 sdb 11348 8501 158830 722452 10742 209487 1759840 1632828 0 83504 2355260
   8      32 sdc 10061 13958 192278 1893236 16748 280811 2378352 2311980 0 114020 4205200
   8      48 sdd 9256 12035 170374 1486700 12202 216977 1831408 1416744 0 103876 2903424
   8      64 sde 11212 36783 383998 184972 7700 98352 846056 796248 0 110604 981204
   8      80 sdf 6557 910 195497 49744 9108 1752 295784 135360 0 147552 185104
   8      81 sdf1 151 307 2056 376 0 0 0 0 0 356 376
   8      82 sdf2 68 0 376 244 1 0 2 24 0 220 268
   8      83 sdf3 6091 378 189289 48708 8305 1752 295782 118776 0 134612 167484
   8      84 sdf4 222 220 3536 364 0 0 0 0 0 328 364
   8      96 sdg 26946 7373 804496 29588 1533 1014 5367309 38884 0 29540 68484
   8      97 sdg1 72 220 2336 8 0 0 0 0 0 8 8
   8      98 sdg2 26550 6790 796912 29308 1531 1014 60949 37048 0 29368 66368
   8      99 sdg3 220 251 3520 68 2 0 5306360 1836 0 1092 1904
   8     128 sdi 540 532 6597 768 5 0 7 76 0 500 844
   8     129 sdi1 151 307 2056 184 0 0 0 0 0 180 184
   8     130 sdi2 72 0 394 136 2 0 4 40 0 176 176
   8     131 sdi3 70 0 371 228 3 0 3 36 0 264 264
   8     132 sdi4 222 220 3536 164 0 0 0 0 0 152 164
   8     112 sdh 120722 1954 51074995 228324 843 0 107680 2188 0 153084 230284
   8     113 sdh1 25955 261 11157892 47204 122 0 16552 212 0 46472 47364
   8     114 sdh2 26102 302 10861700 49932 111 0 22032 240 0 49020 50112
   8     115 sdh3 24309 307 10125716 46412 79 0 21056 420 0 45476 46792
   8     116 sdh4 22327 298 10000772 45648 74 0 7720 224 0 44764 45836
   8     117 sdh5 21899 670 8926947 39088 186 0 40320 692 0 37748 39740
   8     144 sdj 1964 617 50251 15748 10566 2767 333779 319992 0 131608 335740
   8     145 sdj1 151 307 2056 268 0 0 0 0 0 268 268
   8     146 sdj2 82 0 432 232 1460 1014 37997 166464 0 20124 166696
   8     147 sdj3 1484 85 43987 14944 8304 1753 295782 137484 0 110892 152428
   8     148 sdj4 222 220 3536 256 0 0 0 0 0 252 256
  11       0 sr0 0 0 0 0 0 0 0 0 0 0 0
   9       1 md1 33593 0 796226 0 1972 0 60192 0 0 0 0
   9       2 md2 7897 0 232522 0 8009 0 290576 0 0 0 0
   7       0 loop0 0 0 0 0 0 0 0 0 0 0 0
   7       1 loop1 0 0 0 0 0 0 0 0 0 0 0
   7       2 loop2 0 0 0 0 0 0 0 0 0 0 0
   7       3 loop3 0 0 0 0 0 0 0 0 0 0 0
   7       4 loop4 0 0 0 0 0 0 0 0 0 0 0
   7       5 loop5 0 0 0 0 0 0 0 0 0 0 0
   7       6 loop6 0 0 0 0 0 0 0 0 0 0 0
   7       7 loop7 0 0 0 0 0 0 0 0 0 0 0
 253       0 dm-0 73164 0 585288 15108024 2006 0 15600 172 0 25540 15108196
 253       1 dm-1 29695 0 237536 20062264 2692 0 21152 228 0 32040 20062492
 253       3 dm-3 25512 0 204072 20366804 2584 0 20432 352 0 34392 20367156
 253       5 dm-5 23631 0 189024 11409300 925 0 7136 156 0 29472 11409456
 253       7 dm-7 50588 0 404679 670208 5245 0 39624 19720 0 61696 689928
~~~~

`dmsetup status`:

~~~~
lizard_m03: 0 3907029168 writeboost 670053 969264 7632 28173 28172 28172 1 3 21232 0 0 1 4276 0 0 0 1965 0 0 0 589 0 0 33 14 allow_writeback 1 enable_writeback_modulator 1 writeback_threshold 70 nr_cur_batched_writeback 32 sync_data_interval 3600 update_sb_record_interval 0 read_cache_threshold 0
lizard_m02: 0 3907029168 writeboost 811912 969010 7630 44544 44543 44543 1 3 23970 0 0 1 5721 0 0 0 1696 0 0 0 948 0 0 52 14 allow_writeback 1 enable_writeback_modulator 1 writeback_threshold 70 nr_cur_batched_writeback 32 sync_data_interval 3600 update_sb_record_interval 0 read_cache_threshold 0
lizard_m01: 0 3907029168 writeboost 743332 969010 7630 28744 28743 28743 1 3 67675 0 0 1 5485 0 0 0 911 0 0 0 1037 0 2 62 14 allow_writeback 1 enable_writeback_modulator 1 writeback_threshold 70 nr_cur_batched_writeback 32 sync_data_interval 3600 update_sb_record_interval 0 read_cache_threshold 0
lizard_m05: 0 5860533168 writeboost 192532 970280 7640 933597 933596 933596 0 3 47935 0 0 1 2649 0 0 0 3379 0 0 0 1475 0 99 82 14 allow_writeback 1 enable_writeback_modulator 1 writeback_threshold 70 nr_cur_batched_writeback 32 sync_data_interval 3600 update_sb_record_interval 0 read_cache_threshold 0
lizard_m04: 0 3907029168 writeboost 855473 969010 7630 52517 52516 52516 1 3 19789 0 0 1 3838 0 0 0 434 0 0 0 458 0 0 37 14 allow_writeback 1 enable_writeback_modulator 1 writeback_threshold 70 nr_cur_batched_writeback 32 sync_data_interval 1 update_sb_record_interval 0 read_cache_threshold 0
~~~~

Of 5 dm-writeboost devices *drop_caches* hangs on all devices but on `lizard_m05`.

Before attempting `drop_caches` I un-mounted file systems and de-constructed cryptsetup devices. This is on a system with updated kernel `3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux`.

`drop_caches` succeeds on suspended  dm-writeboost devices -- thanks for advise.

#### Question: How to flush cache to HDD (e.g. in case when I want to remove caching SSD forever)?

Something like

    dmsetup suspend wbdev
    dmsetup message wbdev 0 sync_data_interval 1
    dmsetup message wbdev 0 drop_caches
    sleep 1
    dmsetup remove wbdev || dmsetup resume wbdev

**Comment by akiradeveloper** [comment]
By seeing diskstats, I know that no IO is in flight. 

> Of 5 dm-writeboost devices drop_caches hangs on all devices but on lizard_m05.
Yes. `nr_dirty_cache_blocks` in the status line tells us; which is zero on m05 and 1 on others.

> drop_caches succeeds on suspended dm-writeboost devices -- thanks for advise.

You mean you succeeded to `drop_caches` for all lizard_m0x devices? If so, we can say we solve this problem.

The answer to your question depends on what device name you want after removing caching. If you want to continue /dev/mapper/wbdev so filesystem can be ignorant of removing caching, it needs to do some hack (table overwrite). But, If you want to just remove caching, it's easy.

You don't need to set `sync_data_interval` anymore because you suspend the device (which causes flushing) Simple operations can remove caching after dropping all dirty data.

```sh
dmsetup suspend wbdev
dmsetup drop_caches
dmsetup resume wbdev
dmsetup remove wbdev
```

Please read "Remove cache device" in [README](https://github.com/akiradeveloper/dm-writeboost/blob/master/doc/dm-writeboost-readme.txt)

**Comment by onlyjob** [comment]
> You mean you succeeded to drop_caches for all lizard_m0x devices? If so, we can say we solve this problem.

Yes, suspending devices prior to dropping caches helped.

I read README but the removal recipe from there did not work and I still had questions.

The correct way to remove _wbdev_ device seem so be the following:

~~~~
dmsetup suspend wbdev
dmsetup message wbdev 0 drop_caches
dmsetup remove wbdev || dmsetup resume wbdev
~~~~

There is no need to _resume_ device prior to _remove_ but if removing failed (e.g. due to mounted file system etc.) then we need to _resume_ device.

Thank you.
